# 1-sigma fractions per energy after     10 runs
# Z= 41 A= 93
#                               Energies:  10
#  Energy (MeV)     Points Inside Outside Inside fraction
   1.00000E-01           0     0     0     1.00000
   2.00000E-01           0     0     0     1.00000
   5.00000E-01           0     0     0     1.00000
   1.00000E+00           0     0     0     1.00000
   2.00000E+00           0     0     0     1.00000
   3.00000E+00           0     0     0     1.00000
   4.00000E+00           0     0     0     1.00000
   5.00000E+00           0     0     0     1.00000
   8.00000E+00           0     0     0     1.00000
   1.00000E+01           0     0     0     1.00000
#  Energy (MeV)     Points Inside Outside Inside fraction
#   Total                0     0     0     1.00000
